### ISSUE TITLE
Window out of screen ?

### ISSUE THREAD

**Issue by Le-Syl21** [dimusic/active-win-pos-rs#11]
Hi,

I'm under "Ubuntu 22.04.1 LTS"  whit X11 and  I've a big  32/9 screen:

display_info DisplayInfo { id: 446, x: 0, y: 0, width: **5120**, height: **1440**, rotation: 0.0, scale_factor: 1.0, is_primary: true }

if I have 2 separate windows, one taking all place on left on the other on right, I get that:
What I really show on my Screen:
![Capture d’écran du 2022-09-19 21-59-15](https://user-images.githubusercontent.com/67423638/191105992-d2ef25be-12ad-44b3-96d2-df293979cdf0.png)

Now what ActiveWindow SHOW:

LEFT:
active window: ActiveWindow {
    title: "syl21@XPS-8930: ~/projets/debug",
    process_name: "Gnome-terminal",
    window_id: "50331658",
    process_id: 3663,
    position: WindowPosition {
        **x: 140.0,
        y: 14.0,**
        width: 2555.0,
        height: 1453.0,
    },
}

RIGHT:
active window: ActiveWindow {
    title: "",
    process_name: "firefox",
    window_id: "46137405",
    process_id: 4593,
    position: WindowPosition {
        **x: 5158.0,
        y: 8.0,**
        width: 2567.0,
        height: 1465.0,
    },
}

As you can see they are mistake in RIGHT window position, normaly:

-  x would be like 2695.0
-  y would be 14
-  width same as LEFT
-  height same as LEFT

Thx for your help ;-)

**Comment by dimusic** [comment]
Hey thanks for your bug report!
I couldn't try it on the bigger screen on linux and the issue wasn't obvious on the smaller screens so it's really helpful.

I believe the change I pushed in 9e8961eae15c6d4959ea3154fe6e96ee2a2c7907 should fix it.
I compared the output against [xwininfo](https://linux.die.net/man/1/xwininfo) and position seem to match now properly.

The fix is available in the new version 0.7.1.

**Comment by Le-Syl21** [comment]
Thanks, very fast commit :-D

Seem's Better:

LEFT:
syl21@XPS-8930:~$ cd projets/debug/
syl21@XPS-8930:~/projets/debug$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/debug`
display_info DisplayInfo { id: 446, x: 0, y: 0, width: 5120, height: 1440, rotation: 0.0, scale_factor: 1.0, is_primary: true }
Quickly choose your window
active window: ActiveWindow {
    title: "syl21@XPS-8930: ~/projets/debug",
    process_name: "Gnome-terminal",
    window_id: "52428810",
    process_id: 20100,
    position: WindowPosition {
        x: 70.0,
        y: 7.0,
        width: 2555.0,
        height: 1453.0,
    },
}

RIGHT:
syl21@XPS-8930:~/projets/debug$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/debug`
display_info DisplayInfo { id: 446, x: 0, y: 0, width: 5120, height: 1440, rotation: 0.0, scale_factor: 1.0, is_primary: true }
Quickly choose your window
active window: ActiveWindow {
    title: "",
    process_name: "firefox",
    window_id: "8388669",
    process_id: 17109,
    position: WindowPosition {
        x: 2585.0,
        y: 7.0,
        width: 2555.0,
        height: 1453.0,
    },
}
syl21@XPS-8930:~/projets/debug$
