### ISSUE TITLE
MacOS get_active_window() only returning the same process_name

### ISSUE THREAD

**Issue by js-jitsu** [dimusic/active-win-pos-rs#12]
I am running a loop and calling this function get_active_window().
The process_name is only returning the same value while I am switching through different windows.

**Comment by dimusic** [comment]
Looks like you won't get updates if you run it in a loop on MacOS until you subscribe to the [NSWorkspaceDidDeactivateApplicationNotification](https://developer.apple.com/documentation/appkit/nsworkspace/1526159-diddeactivateapplicationnotifica) in your app. However, I can't confirm or provide any examples of doing that with Rust, if you figure it out I'd love to see it.

I tried to run it in a loop in the context of a [tauri](https://tauri.app/) app and I was receiving updates when switching between apps just fine which tells me it's not an issue with the lib.

I might look into it a bit more later and come up with simple example for this case but I'll close the issue for now.

**Comment by js-jitsu** [comment]
@dimusic ok, I also tried running within a loop on a tauri app.
are you also on Mac? I was not getting the process_name value to change.

**Comment by dimusic** [comment]
@js-jitsu How are you running your loop? Is it just process_name value that's not changing for you or the whole object?

This is an example of the tauri setup using tauri async runtime and tokio that I've tried on a mac and it works:

```rust
fn main() {
    tauri::Builder::default()
        .setup(|_app| {
            tauri::async_runtime::spawn(async move {
                let loop_handle = tokio::spawn(async move {
                    loop {
                        match get_active_window() {
                            Ok(win) => {
                                println!("win {:?}", win);
                            }
                            Err(err) => {
                                println!("err {:?}", err);
                            }
                        };

                        tokio::time::sleep(std::time::Duration::from_secs(1)).await;
                    }
                });

                loop_handle.await.unwrap();
            });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Getting active window in a blocking loop will always return the same window on macos.

**Comment by js-jitsu** [comment]
@dimusic omg thank you! I've spent so much time trying this lol

**Comment by medzernik** [comment]
is there any way of getting updates without using tauri?

**Comment by dimusic** [comment]
@medzernik I was curious about it too and after playing around for a bit it seems the only way to receive updates for your app on mac os is to explicitly subscribe to the [NSWorkspaceDidActivateApplicationNotification](https://developer.apple.com/documentation/appkit/nsworkspacedidactivateapplicationnotification)

I put together a quick example you can find here - https://github.com/dimusic/active-window-macos-example
