### ISSUE TITLE
Process name isn't the process name

### ISSUE THREAD

**Issue by medzernik** [dimusic/active-win-pos-rs#13]
Using the value <window>.process_name can result in wrong process name. For example:

```
STRING LANG CODE: \StringFileInfo\040904b0\FileDescription
DESCRIPTION: Visual Studio Code
DESCRIPTION_NEW: Visual Studio Code
active window: ActiveWindow {
    title: "active-window.rs - active-win-pos-rs - Visual Studio Code",
    process_name: "Visual Studio Code",
    window_id: "HWND(1968720)",
    process_id: 5576,
    position: WindowPosition {
        x: -7.0,
        y: -7.0,
        width: 2062.0,
        height: 1166.0,
    },
}
STRING LANG CODE: \StringFileInfo\040904e4\FileDescription
DESCRIPTION: VLC media player
DESCRIPTION_NEW: VLC media player
active window: ActiveWindow {
    title: "VLC media player",
    process_name: "VLC media player",
    window_id: "HWND(1314976)",
    process_id: 26212,
    position: WindowPosition {
        x: -1150.0,
        y: 333.0,
        width: 781.0,
        height: 628.0,
    },
}
```

![image](https://user-images.githubusercontent.com/1900179/227922591-f3e5695a-0837-4e05-8a21-4129486dcd3e.png)

![image](https://user-images.githubusercontent.com/1900179/227922624-e51e246f-f969-42af-be53-a2d3d4054ad8.png)

The actual process names are different. I located the issue to this request:
https://github.com/dimusic/active-win-pos-rs/blob/2a3764db34ababfb5aeee74d845f5e9d18236b9e/src/win/platform_api.rs#L182

This line requests the `FileDescription`, which can differ from process name. One possible fix is to change this to `InternalName`, but this results in anomalies:

```
STRING LANG CODE: \StringFileInfo\040904b0\InternalName
DESCRIPTION: electron.exe
DESCRIPTION_NEW: electron.exe
active window: ActiveWindow {
    title: "active-window.rs - active-win-pos-rs - Visual Studio Code",
    process_name: "electron.exe",
    window_id: "HWND(1968720)",
    process_id: 5576,
    position: WindowPosition {
        x: -7.0,
        y: -7.0,
        width: 2062.0,
        height: 1166.0,
    },
}
```

VSCode is clearly not Electron.exe in the process tab.

I have a solution I will link to a PR, that is to use a completely different function to get data:
```
active window: ActiveWindow {
    title: "active-window.rs - active-win-pos-rs - Visual Studio Code",
    process_name: "Code.exe",
    window_id: "HWND(1968720)",
    process_id: 5576,
    position: WindowPosition {
        x: -7.0,
        y: -7.0,
        width: 2062.0,
        height: 1166.0,
    },
}
```

**Comment by dimusic** [comment]
Yeah that's a good point, looks like `process_name` was not the best name for what it returns. 
I like your solution, but I think we could use both values. The old `process_name` could be renamed to `app_name` or something like that?
Also if the `process_name` would now always match the executable name we might as well return the complete path to it.

**Comment by medzernik** [comment]
> Yeah that's a good point, looks like `process_name` was not the best name for what it returns. I like your solution, but I think we could use both values. The old `process_name` could be renamed to `app_name` or something like that? Also if the `process_name` would now always match the executable name we might as well return the complete path to it.

I tried to implement this here: 1178afa
