### ISSUE TITLE
ActiveWindow does not implement PartialOrd, Clone and Default

### ISSUE THREAD

**Issue by medzernik** [dimusic/active-win-pos-rs#17]
These traits are very simple to implement and help a lot with using the data structures

**Comment by dimusic** [comment]
I pushed a change to implement Clone, Default and PartialEq for ActiveWindow. Let me know if that covers your needs.
I'm not exactly sure how would PartialOrd work here unless you meant PartialEq?

**Comment by medzernik** [comment]
yeah its partialEQ :D thanks!
