### ISSUE TITLE
A way to subscribe to new active window event?

### ISSUE THREAD

**Issue by sandric** [dimusic/active-win-pos-rs#18]
Hi, I was curious if its possible to implement `subscribing` to active window change event somehow? The thing is I know how to do this on linux, have vague understanding how to make it with winapi, but have any clue how (if at all possible) to do this for OSX.
I'm asking because polling is quite expensive, especially in OSX for some reason, and I can't find any library that could do this for some reason.
Thx.

**Comment by dimusic** [comment]
I don't really have plans to implement subscribing at this point.

How bad is the performance you're seeing on OSX? I just checked and I'm getting results in around 0.2-0.3 ms on linux and windows and closer to 1 ms on a mac while running in a loop which is fine for me.
