### ISSUE TITLE
napi-rs node pre-compilation

### ISSUE THREAD

**Issue by tom2strobl** [dimusic/active-win-pos-rs#20]
Hi there! I'm interested in using `active-win-pos-rs` from within `electron` which should be rather trivial nowadays with [NAPI-RS](https://napi.rs/), do you by any chance have already plans for doing this on your end or do you want to stay in rust-land and rather have somebody else do it?

Those type of only-glue-repos in some cases tend to get more attention than the actual implementation which is unfair, that's why I'm asking.

✌🏻

**Comment by dimusic** [comment]
I don't have plans to support bindings to other languages like that. If you or somebody else wants to do it that's totally fine.

For Nodejs however, you might want to check out [active-win](https://github.com/sindresorhus/active-win) package which does the same thing and is a bit more stable

**Comment by tom2strobl** [comment]
Thanks for the heads up!
