### ISSUE TITLE
failed to run custom build command for `appkit-nsworkspace-bindings v0.1.0`

### ISSUE THREAD

**Issue by Srini-B** [dimusic/active-win-pos-rs#24]
Hi, I'm getting the following error on Xcode 15, which has macOS 14 SDK, Apologies if it's not related here

Caused by:
  process didn't exit successfully: `/Users/cyron/Documents/BeeBox/sandclock-tauri/src-tauri/target/debug/build/appkit-nsworkspace-bindings-dd1fe9d906edfc67/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=framework=AppKit

  --- stderr
  thread 'main' panicked at '"wait_struct_(unnamed_at_/Applications/Xcode_app/Contents/Developer/Platforms/MacOSX_platform/Developer/SDKs/MacOSX14_0_sdk/usr/include/sys/wait_h_199_2)" is not a valid Ident', /Users/cyron/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.67/src/fallback.rs:774:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by dimusic** [comment]
Thanks for pointing it out! Updating bindgen to the latest version seems to have fixed the issue.

I've published new version 0.8.2 with the fix

**Comment by Srini-B** [comment]
Thanks for your effort. Is it possible to get url if the active window is a browser. 
Accessibility permissions may be needed for that on macOS(based on what I used in electron)
