### ISSUE TITLE
Resizing and setting position

### ISSUE THREAD

**Issue by LastxTemplar** [dimusic/active-win-pos-rs#26]
Hi,
I am new to rust and still trying to understand what's what :)
Is it possible the manipulate the active window in any way? like setting the size or position?

I found this https://tauri.app/v1/api/js/window but it seems to only be geared towards the windows that are part of the main app?

Thank you!

**Comment by dimusic** [comment]
Sorry didn't have time to properly look into your question. Manipulating the active window is not in the scope of this library and the implementation would depend on the platform. I can't really give you any tips on that.
