### ISSUE TITLE
[Feature Request] Specific Process Information by Name/Executable

### ISSUE THREAD

**Issue by Miniontoby** [dimusic/active-win-pos-rs#29]
Hi,

Would it be possible to just get the info of a specific process? Just by the process name/executable?

I want to be able to get the title of a specific program and the title changes depending on where you are in the program.

Kind regards,
- Miniontoby

**Comment by dimusic** [comment]
This library won't let you subscribe to the title changes of a specific process and I'm not planning to add this functionality. 

Can't you just poll the active window with a small interval and check if it belongs to the app you're looking for by using `app_name` or `process_path`?

**Comment by Miniontoby** [comment]
That is what I wanted!

I didn't suggest to subscribe to events...

I was already planning to just poll, but this repo seems to only allow to
get the active window but not a specific one...

But idk how to do it if it is possible


This library won't let you subscribe to the title changes of a specific
> process and I'm not planning to add this functionality.
>
> Can't you just poll the active window with a small interval and check if
> it belongs to the app you're looking for by using app_name or process_path
> ?.
>

**Comment by dimusic** [comment]
ok yeah for that you'll have to go through all processes and find the one you need. But that's not something I would want to add to this library.
For windows you'd probably want to use [EnumProcesses](https://learn.microsoft.com/en-us/windows/win32/psapi/enumerating-all-processes?redirectedfrom=MSDN)
For other platforms there's got to be something similar.
Hope this helps.
