### ISSUE TITLE
Doesn't change active window when switching windows (MacOS)

### ISSUE THREAD

**Issue by mpm896** [dimusic/active-win-pos-rs#31]
Hello, 

I'm attempting to write a small program that mimics Linux's highlight text to copy, middle click to paste behavior (similar to this [repo](https://github.com/lodestone/macpaste/tree/master), but using Rust), but I'm having issues with getting the active window. When I run the program (from Terminal or from VSCode), it sets the first window I click as the active window, but if I try to use a different window, it keeps the original widow as the front active window.

For example, when running from Terminal, I'll switch to Google Chrome and then that will be set as the active window (and I can select text, etc). But if I switch back to the Terminal, it keeps Google Chrome as the active window and thus I cannot select text from the terminal. 

I would love any advice on how to properly get the active window, even when switching between windows. Thanks!

**Comment by dimusic** [comment]
On MacOS your app needs to explicitly subscribe to the [NSWorkspaceDidActivateApplicationNotification](https://developer.apple.com/documentation/appkit/nsworkspacedidactivateapplicationnotification) to receive updates.

I've setup a basic example that does that at some point. You can find it [here](https://github.com/dimusic/active-window-macos-example)

Closing the issue, but feel free to reopen or comment if you run into any problems.
