### ISSUE TITLE
Expanding the capabilities of this library

### ISSUE THREAD

**Issue by omerdn1** [dimusic/active-win-pos-rs#7]
Love the approach and implementation on this!

I was wondering if you'd be willing to extend the capabilities to allow for fetching of additional window information like window name, class, instance, etc..

If you're interested, I prefer to incrementally add these additions to this repo instead of forking.

**Comment by dimusic** [comment]
Getting window title has already been implemented for windows (#3) and linux and available on the main branch. It will be available in a new release soon once I figure out a few issues with macos.

I'd be happy to add more stuff to the output. Feel free to make a pull request if there's a feature you can add.
